version: '3.4'

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - .env
      - .env.local
    volumes:
      - reading-log-db:/var/lib/postgresql/data
      - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db

  backend:
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
    build:      
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
        - db

volumes:
  reading-log-db:
